# Generated by Django 2.2.7 on 2019-11-15 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
