# Generated by Django 2.2.7 on 2019-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0002_auto_20191115_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
