# Generated by Django 2.2.7 on 2019-11-16 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakkospakki', '0004_auto_20191115_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
