# Generated by Django 2.2.7 on 2019-11-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0005_housingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='building_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
