# Generated by Django 2.2.7 on 2019-11-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0009_auto_20191116_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='housing_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='kakkospakki.HousingManager'),
        ),
    ]
