# Generated by Django 2.2.7 on 2019-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0010_job_housing_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('foreman', 'foreman'), ('project_manager', 'project_manager'), ('worker', 'worker')], max_length=64)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(null=True, related_name='jobs', to='kakkospakki.Employee'),
        ),
    ]
