# Generated by Django 2.2.7 on 2019-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0012_auto_20191116_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='kakkospakki.Employee'),
        ),
    ]
