# Generated by Django 2.2.7 on 2019-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0013_auto_20191116_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('in_progress', 'in progress'), ('on_hold', 'on hold'), ('finished', 'finished')], max_length=64),
        ),
    ]
