# Generated by Django 2.2.7 on 2019-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakkospakki', '0014_auto_20191116_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='+358505330252', max_length=64),
        ),
    ]
